# ########################################################### #
# Daily Shop Plugin Developer: PopoGonry ( rhtjdsh35@gmail.com )
# ########################################################### #

# Daily Shop Plugin Config File #

Daily-Shop-Name: "ShopName"


# {가격} / {개인잔여수량} / {개인최대수량} / {전체잔여수량} / {전체최대수량} / {돈} #

Item-Lore:
  - "&6&l좌클릭 &f&l으로 아이템을 구매합니다."
  - "&f&l가격 : &6&l{가격}&f&l원"
  - "&f&l개인 잔여 횟수 : &6&l{개인잔여수량}&f&l개"
  - "&f&l개인 최대 횟수 : &6&l{개인최대수량}&f&l개"
  - "&f&l전체 잔여 횟수 : &6&l{전체잔여수량}&f&l개"
  - "&f&l전체 최대 횟수 : &6&l{전체최대수량}&f&l개"
  - "&f&l플레이어 돈 : &6&l{돈}&f&l원"



